export default {
    translations: {
        kit: {
            noDropdownOptions: 'Нет доступных опций',
            cantLoadOptions: 'Не удалось загрузить опции',
            dropdownPlaceholder: 'Выберите значение',
            selected: 'Выбраны:',
            apply: 'Применить',
        },
        salesInvoice: 'Расходная\nнакладная',
        reports: 'Отчёты',
        inventory: 'Инвентаризация',
        storage: 'Хранение',
        orders: 'Заказы',
        enteringBalance: 'Ввод\nостатков',
        drugLabeling: 'Маркировка\nлекарств',
        addDocument: 'Добавить документ',
        getParameters: 'Подобрать параметры',
        filterInputPlaceholder: 'Найти документ',
        search: 'Поиск',
        filtersBarModalTitle: 'Подбор параметров поиска',
        actions: 'Действия',
        nomenclature: 'Номенклатура',
        documentNo: 'Номер документа',
        documentDate: 'Дата документа',
        dateFrom: 'Дата с',
        dateTo: 'Дата по',
        documentReason: 'Основание',
        fundingSource: 'Источник финансирования',
        warehouse: 'Склад',
        status: 'Статус',
        balance: 'Остаток',
        gtin: 'GTIN',
        sgtin: 'sGTIN',
        from: 'от',
        branch: 'Отделение',
        supplier: 'Поставщик',
        consignor: 'Грузоотправитель',
        consignee: 'Грузополучатель',
        contract: 'Контракт',
        remark: 'Примечание',
        comissionChief: 'Председатель комиссии',
        comissionMembers: 'Члены комиссии',
        nomenclatureName: 'Наименование номенклатуры',
        series: 'Серия',
        measurementUnit: 'Единица измерения',
        expirationDate: 'Годен до',
        expirationTerm: 'Дней до конца срока годности',
        numberOfUnits: 'Количество единиц',
        numberOfPieces: 'Количество штук',
        quantityStorage: 'Количество по учету',
        quantityFact: 'Количество по факту',
        shortage: 'Недостача',
        unitPriceWithTaxes: 'Цена за ед. товара с НДС',
        amountWithTax: 'Сумма с НДС',
        amountWithoutTax: 'Сумма без НДС',
        amountTotal: 'Сумма всего',
        taxRate: 'Ставка НДС',
        storagePlace: 'Помещение, область хранения, участок',
        total: 'Всего',
        yes: 'Да',
        no: 'Нет',
        save: 'Сохранить',
        saveAndProceed: 'Сохранить и провести',
        open: 'Открыть',
        add: 'Добавить',
        today: 'Сегодня',
        proceed: 'Продолжить',
        cancel: 'Отменить',
        confirm: 'Подтвердить',
        writeOff: 'списать',
        next: 'Далее',
        setFilters: 'Далее',
        newNomenclature: 'Новая номенклатура',
        addNomenclatures: 'Добавить номенклатуры',
        transactDocument: 'Провести',
        edit: 'Редактировать',
        remove: 'Удалить',
        print: 'Распечатать',
        tryAgain: 'Попробовать ещё раз',
        datePlaceholder: 'Введите дату',
        inputPlaceholder: 'Введите значение',
        ensureSaveEmptyDocTitle: 'Документ не содержит данных о номенклатуре. Вы хотите его сохранить?',
        ensureSaveEmptyDocLabel: 'Больше не показывать данное сообщение',
        transacted: 'проведён',
        notTransacted: 'не проведён',
        nomenclaturesData: 'Данные номенклатур',
        addNomenclaturesTitle: 'Добавление номенклатур',
        editNomenclatureTitle: 'Редактирование номенклатуры',
        chooseReportType: 'Выберите тип отчётности',

        expireDate: 'Дата истечения',
        expired: 'Просрочено',
        rangeDate: 'От текущей даты до',
        reportTypes: {
            balance: 'Отчёт об остатках',
            expirationDate: 'Отчет о сроках годности',
            byDate: 'Истекает на дату',
            expired: 'C истекшим сроком годности',
            byRange: 'Истекает в диапазоне',
        },

        purchaseInvoice: {
            label: 'Приходная\nнакладная',
        },

        formErrors: {
            require: 'Заполните поле',
            positiveNumber: 'Введите положительное число',
            id: 'Заполните поле номер документа',
            date: 'Заполните  поле дата накладной',
            supplier_id: 'Заполните поле поставщика',
            reason_id: 'Заоплните поле основание',
            consignor_id: 'Заполните поле грузоотправитель',
            consignee_id: 'Заполните поле грузополучатель',
            contract_number: 'Заполните поле контракт',
            financial_source_id: 'Заполните поле источник финансирования',
            warehouse_id: 'Заполните поле склад',
            comission_chief_id: 'Заполните поле председатель комиссии',
            comission_members: 'Заполните поле члены комиссии',
        },

        createNomenclature: {
            title: 'Создание номенклатуры',
            name: 'Торговое наименование',
            internationalName: 'МНН',
            latinName: 'Латинское наименование',
            dosageForm: 'Лекарственная форма',
            dosage: 'Дозировка',
            packing: 'Фасовка',
            packaging: 'Упаковка',
            country: 'Страна',
            manufacturer: 'Производитель',
            unit: 'Единица измерения',
            nds: 'Ставка НДС',
            type: 'Тип медикамента',
            createSuccess: 'Номенклатура успешно записана в базу данных',
            createError: 'Не удалось записать данные в базу:',
        },

        editBalanceInvoice: {
            title: 'Документ',
            invoiceData: 'Данные документа',
            savingTitle: 'Сохранение документа',
            savingSuccess: 'Документ успешно сохранен',
            savingError: 'Не удалось сохранить документ:\n',
        },

        editPurchaseInvoice: {
            title: 'Приходная накладная №',
            cargoData: 'Данные о грузе',
            invoiceData: 'Данные приходной накладной',
            savingTitle: 'Сохранение приходной накладной',
            savingSuccess: 'Приходная накладная успешно сохранена',
            savingError: 'Не удалось сохранить приходную накладную:\n',
        },

        editInventory: {
            title: 'Создание документа инвентаризации',
            documentData: 'Данные документа',
            savingTitle: 'Сохранение документа инвентаризации',
            savingSuccess: 'Документ инвентаризации успешно сохранен',
            savingError: 'Не удалось сохранить документ инвентаризации:\n',
        },

        reportsPage: {
            formModalTitle: 'Выберите параметры формирования отчета',
            balanceTitle: 'Отчет о движении лекарственных средств',
            expirationDateTitle: 'Отчет о сроках годности',
            expiredReportSubType: 'С истёкшим сроком годности',
            byDateReportSubType: 'Срок годности истекает на дату: {{dateTo}}',
            byRangeReportSubType: 'Срок годности истекает в диапазоне: {{dateFrom}} - {{dateTo}}',
        },

        editSalesInvoice: {
            title: 'Создание расходной накладной',
            salesData: 'Данные расходной накладной',
            numberDoc: 'Номер документа',
            enterNumberDoc: 'Введите номер документа',
            reasonForDebiting: 'Причина списания',
            createSalesInvoiceAddNomenclature: 'Создание расходной накладной. Добавление номенклатуры',
            searchNamenclature: 'Поиск по номенклатуре',
            action: 'Выбор',
            storageArea: 'Помещение',
            unitPrice: 'Цена за ед. товара с НДС',
            priceWithoutTax: 'Cумма без НДС',
            priceWithTax: 'Cумма с НДС',
            savingTitle: 'Сохранение расходной накладной',
            savingSuccess: 'Расходная накладная успешно сохранена',
            savingError: 'Не удалось сохранить расходную накладную:\n',
            errors: {
                id: 'Заполните поле номер накладной',
                date: 'Заполните поле дата накладной',
                warehouse_id: 'Заполните поле склад',
                enterprise: 'Заполните поле отделение',
                write_of_reason: 'Заполните поле причина списания',
                document_number: 'Заполните поле номер документа',
            },
        },
    }
};
